[Unit]
Description=ydotool keyboard daemon for Speech Note
ConditionPathExists=/dev/uinput

[Service]
RuntimeDirectory=ydotool
RuntimeDirectoryMode=0700
ExecStart=
ExecStart=/usr/bin/ydotoold --mouse-off --socket-path=%t/ydotool/socket --socket-perm=0600
Restart=on-failure
RestartSec=2
